### ISSUE TITLE
Odd manipulation of configmap with Istio

### ISSUE THREAD

**Issue by Timoses** [replicatedhq/ship#1008]
### Expected behavior
Working Istio Sidecar Injector

### Actual behavior
Istio Sidecar Injector failed due to odd config map manipulation on the side of Ship.

### Information

- Ship version: 0.44.0
- Docker version: 18.06.2-ce
- Command line run: 

### Steps to reproduce the behavior

See step **How was Istio installed?** in https://github.com/istio/istio/issues/15152

Ship apparently edited `initContainers: \n` into `initContainers: []\n` (as one example).

See https://github.com/istio/istio/issues/15152 for more information.

**Comment by laverya** [comment]
Interesting - I thought we had some code to handle that (specifically empty or comment-filled lines following a `:`) and it seems to be failing here.

The reason we have such code _at all_ is that quite a few helm charts produce things that are not in fact valid yaml, and kustomize balks when presented with such.

Would you be willing to share the helm config used here?

**Comment by Timoses** [comment]
The following should already produce the error:
```
ship init https://github.com/istio/istio/tree/1.2.0/install/kubernetes/helm/istio
grep "initContainers:" rendered.yaml
```
yields `}}\n  initContainers: []\n`

**Comment by Timoses** [comment]
> The reason we have such code at all is that quite a few helm charts produce things that are not in fact valid yaml, and kustomize balks when presented with such. It's really not my favorite piece of ship, [...]

Perhaps it would be better to get Helm to "fix" it? Imo, the only thing that ship should do is play the mediator (`helm template` -> `kustomize`).

**Comment by laverya** [comment]
@Timoses just saw this again - I need to fix my github notification settings
I'll take a look tonight/tomorrow

**Comment by laverya** [comment]
Oh, this makes a lot more sense after looking at it further
The edit made by ship is to the data within a configmap that has not yet been templated

So there are two ways I can see to fix this
One is to have this find/replace code recognize the contents of strings and avoid editing them, which would be ideal (but may not be practical)
The other (easier IMO) solution would be to have ship recognize the beginning of untemplated strings and accept that as a child item

**Comment by laverya** [comment]
The "recognize unexecuted template functions" fix has been merged and will be in the next release @Timoses
