### ISSUE TITLE
Cannot ship update if upstream directory already exists

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#1013]
Using ship 0.47.3 with a replicated.app upstream. Ship init works. The application is using proxied github assets (all pointing to "master" for the ref).

When running ship update, the upstream isn't updated. If I rm -rf upstream, then run ship init, the upstream is updated.

Expected behavior: ship init should update the upstream on disk, even if it already exists.

**Comment by laverya** [comment]
I believe this was fixed as part of the v0.50.0 release, specifically with PR https://github.com/replicatedhq/ship/pull/1040.
