### ISSUE TITLE
Template function ShipCustomerRelease in config map produces error data too long

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/ship#1064]
### Expected behavior

I should be able to follow this guide for a titled installation https://help.replicated.com/docs/ship/playbooks/entitlements/

### Actual behavior

When i try to deploy the release yaml I get the following error:

```
The ConfigMap "titled" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

### Information

- Ship version: 0.51.0
- Command line run: ship init replicated.app/myslug

**Comment by laverya** [comment]
As a fix, I'm going to drop Github data (and private image data) from `ShipCustomerRelease` to form a new function `ShipCustomerReleaseMinimal`. This should greatly reduce the size of the annotation produced here

**Comment by emosbaugh** [comment]
does this require the ship app to change the k8s config map yaml? something to consider

**Comment by laverya** [comment]
It does
The alternative is to just remove those fields from `ShipCustomerRelease`, which might break things too (but I don't know of any use case that would require those fields to be exposed in such a way)
