### ISSUE TITLE
RFC: Ship init should not require that state be removed on re-run

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#374]
This is a UX change we want to make from the behavior introduced around ship init vs update.

### Expected behavior

When running `ship init` with an existing `.ship/state.json`, ship should prompt and ask the user if they'd like to continue, or start from scratch. If they choose to continue, they should get the normal `ship init` experience, but with the values, overlays, etc. they created the last time around.

### Actual behavior

When running `ship init` with an existing `.ship/state.json`, ship prompts the user to start from scratch, or exit.

### Questions/Implementation Notes

`ship init` should still always require a `target` like a github.com url to a chart, even if there's a chart URL in the state.json. If the target doesn't match whats in the state.json, *then* we should require them to remove the state.

We don't currently implement `ship update --headed`, but `ship init` with existing state should essentially do the same thing as `ship update --headed`

### Information

- Ship version: 6789bee
- Command line run: `ship init github.com/helm/charts/stable/spinnaker`

### Steps to reproduce the behavior

1. run `ship init ...` and walk through entire flow, exit ship
2. run `ship init ...` again, see prompt for "you must remove state to continue"

**Comment by marccampbell** [comment]
The proposal today is to make `ship init` use the `ship update` workflow if an existing state is found, but default to `--headed`.

**Comment by Rob0h** [comment]
`--preserve-state` flag has been added in #794 to use the existing `state.json`. the lifecycle will then follow `ship update --headed`
