### ISSUE TITLE
Ship Navcycle should support Kubectl lifecycle steps

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#434]
### Expected behavior

Terraform works in navcycle

### Actual behavior

Right now, the headed implementation of Terraform/Kubectl lifecycle
steps is not wired up.

### Information

- Ship version: 0.13.2
- Docker version: 
- Command line run: Dont have an example offhand

### Steps to reproduce the behavior

1. Right a release with a kubectl lifecycle step
2. Navigate through to kubectl steps in UI

**Comment by marccampbell** [comment]
@laverya I believe this issue has been resolved for a while. Is there anything let remaining?

**Comment by marccampbell** [comment]
This was addressed in #590
