### ISSUE TITLE
Github assets with source:public should not go through the replicated API

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#455]
### Expected behavior
Public assets are pulled from github.

### Actual behavior
Public assets are pulled from github via the Replicated API

### Information

- Ship version: 0.13.3 https://github.com/replicatedhq/ship/commit/f89c9bfcd4cc851223212e773626b2e7bff97cf1

**Comment by marccampbell** [comment]
Ship 0.25.0 added a `proxy: <boolean>` to solve this. GitHub asset types with `proxy: false` will not be proxied through the Replicated API.
