### ISSUE TITLE
Helm values in ship init should show comments

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#473]
### Expected behavior
When running ship init <helm>, the helmValues step should show the values.yaml, with comments, exactly as the repo contains.

### Actual behavior
The keys are stripped from the values.yaml, and shown without comments.

### Information

- Ship version: 44e24a4
- Command line run: `ship init github.com/helm/charts/stable/grafana`

**Comment by jadengore** [comment]
@divolgin is this issue addressed?

**Comment by emosbaugh** [comment]
#706
