### ISSUE TITLE
There should be a way to use a github api token for github requests

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#477]
### Expected behavior
A github api token is used and the api rate limits are 5k/hr
Perhaps it should be read from an environment variable?

### Actual behavior
No github api token is used and the api rate limits are 60/hr/ip

### Information

See [github api docs](https://developer.github.com/v3/#rate-limiting).

- Ship version: master as of https://github.com/replicatedhq/ship/commit/6f3dd933085e219e51cbc50c71c8e008bd892a7e
- Docker version: irrelevant
- Command line run: `ship init github.com/better-db/chart`

### Steps to reproduce the behavior

1. run `ship init github.com/better-db/chart` 61x over a few minutes  
2. observe as `403 Forbidden` errors begin showing up

**Comment by marccampbell** [comment]
Resolved in #723
