### ISSUE TITLE
Don't include extra attributes in metadata when creating a patch

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#480]
### Expected behavior
Creating a patch in ship init, the minimal attributes necessary should be included in the patch.

### Actual behavior
`labels` are included in metadata.

### Information

- Ship version: efb845c

### Steps to reproduce the behavior

1. create a patch by clicking on a deployment
2. see the tiller labels in the patch

**Comment by Rob0h** [comment]
It seems that when the `labels` are removed and the patch is applied -  the labels are removed from the overlay. I can remove the labels from the UI and add them only when the overlays are finalized. However, that seems too "magic" and you would be unable to change the labels. Thoughts?

**Comment by marccampbell** [comment]
@Rob0h Agreed. This feels unnecessary and the "magic" that it would introduce likely would cause more confusion. I vote to close this issue, and address it if a similar issue comes up in the future.
