### ISSUE TITLE
`Dest` for Kustomize lifecycle step is not linted correctly

### ISSUE THREAD

**Issue by Rob0h** [replicatedhq/ship#533]
### Expected behavior
- `Dest` of `Kustomize` lifecycle event is mandatory and is checked via lint

### Actual behavior
- `Dest` is not linted for in the `Kustomize` lifecycle step
- `Dest` is not defaulted and will cause the step to hang

### Information

- Ship version: f28ee03a9579d11255f8594c123cc4a11c7483a7
- Docker version: N/A
- Command line run: N/A

### Steps to reproduce the behavior

1. Run `init` command against existing lifecycle configured in console

**Comment by laverya** [comment]
@Rob0h while I'm looking at this, are there any other required properties for the Kustomize step?
