### ISSUE TITLE
Cannot skip kustomize step

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#539]
### Expected behavior
On the kustomize steps, it shouldn't be required to create a patch.

### Actual behavior
If you click into a file to look at the YAML, there's no way to proceed without creating a patch.

### Information

- Ship version: 4e0aa5a

### Steps to reproduce the behavior

1. ship init <helm>
2. advance to the kustomize step
3. Click to look at a file
4. No way to continue

**Comment by laverya** [comment]
I feel like this isn't the first time we've had this issue. Definitely something that should go in the E2E testing for ship init @jadengore

**Comment by GraysonNull** [comment]
I wonder if this shouldn't be labeled a bug but rather an enhancement. Nothing is wrong functionally, there's just the lack of ability to perform a task. I can get this updated today
