### ISSUE TITLE
Ship init UI CSS should be scoped to component

### ISSUE THREAD

**Issue by 10Dimensional** [replicatedhq/ship#572]
### Expected behavior
The UI component CSS should only be scoped to the component, so as not to introduce global styles that could conflict with the parent.

### Actual behavior
Currently, the UI uses a lot of global reset and and base styles attached to body and html tags. These styles need to be removed. All styles should be scoped to the root div `#ship-init-component`.

### Information

- Ship version: [3aa19e9](https://github.com/replicatedhq/ship/commit/3aa19e90e80f293c2eaf0f5e121fae3246bff6c4)
- Command line run: `yarn start`

### Steps to reproduce the behavior

1. Run the UI in dev mode

**Comment by jadengore** [comment]
@10Dimensional Is this addressed?
