### ISSUE TITLE
Ship should work with single file upstreams

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#644]
### Expected behavior
Many kubernetes applications are distributed as multi-doc yaml files or `kind: List`. Ship should be able to use these files as upstreams. An example would be `https://raw.githubusercontent.com/honeycombio/kubernetes-manifests/master/logs/quickstart.yaml` or `https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/jaeger-production-template.yml`.
### Actual behavior
Ship fails midway through with an error `... write base kustomization: Base directory is empty` (in the case of jaeger) or does not allow kustomize overlays to be created (in the case of honeycomb)
### Information

- Ship version: latest
- Docker version: ...
- Command line run: 

### Steps to reproduce the behavior

1. run `ship init https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/jaeger-production-template.yml`
2. click 'continue' in step 2
3. observe error popup

**Comment by dexhorthy** [comment]
@laverya I think this may have been addressed at this point -- running 

```
ship init https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/jaeger-production-template.yml
```

no longer produces an error

**Comment by laverya** [comment]
This has been resolved.
