### ISSUE TITLE
Homebrew recipe not updated on release

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#652]
### Expected behavior

`brew upgrade ship` installs the latest version, (0.19.0 currently)

### Actual behavior

`brew upgrade ship` thinks the latest version of ship is 0.16.0

```
$  brew upgrade ship
Error: replicatedhq/ship/ship 2200e0dd8365a4b02f47d1536f5a6c4a5f3f3563 already installed
$ ship version
{
    "version": "0.16.0",
    "git": "1dc2578",
    "buildTime": "2018-10-03T21:07:09Z"
}
```

**Comment by laverya** [comment]
That's not the behavior I've experienced:
```
~$ brew upgrade ship
Error: replicatedhq/ship/ship 0.19.0 already installed
~$ ship version
{
    "version": "0.19.0",
    "git": "bebf32f",
    "buildTime": "2018-10-18T21:04:40Z"
}
```

I think you added the tap before I did, that might explain the issues

**Comment by dexhorthy** [comment]
Strange. Okay. Got it to work via 

```
brew uninstall --force ship
```

and then reinstalling. Will close this for now, and reopen if it fails again on the next release.
