### ISSUE TITLE
Ship should persist terraform state

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#656]
### Expected behavior
Terraform state is contained within ship state

### Actual behavior
Terraform state is contained within a file in the relevant folder

### Information

- Ship version: 0.20.0

**Comment by dexhorthy** [comment]
+1 on this. The feature wont really be ready for production use until this is done.

**Comment by laverya** [comment]
I see three ways to do this:
1. The terraform lifecycle step writes the tfstate to the relevant folder before Terraform runs, and backs it up afterwards
2. We implement an [HTTP backend](https://www.terraform.io/docs/backends/types/http.html) for Terraform and use that
3. We implement a custom backend of some sort (I am not positive Terraform supports custom backends)
