### ISSUE TITLE
Ship watch is broken in 0.23.0

### ISSUE THREAD

**Issue by fshot** [replicatedhq/ship#693]
### Expected behavior
after a successful ship init, ship watch should block until an upstream change is detected

### Actual behavior
after a successful ship init, ship watch immediately fails

### Information

- Ship version: 0.23.0
- Docker version: ...
- Command line run:
```
ship init https://github.com/helm/charts/tree/master/stable/datadog
ship watch
```
### Steps to reproduce the behavior

1. ship init https://github.com/helm/charts/tree/master/stable/datadog
2. ship watch
3. Error: Could not determine application type of upstream https://github.com/helm/charts/tree/master/stable/datadog\ngithub.com/replicatedhq/ship/pkg/specs

**Comment by laverya** [comment]
Fixed by #697, part of release [0.24.0](https://github.com/replicatedhq/ship/releases/tag/v0.24.0). A basic `ship watch` sanity check has been added to the `init` and `init_app` integration test suites to hopefully catch similar regressions in the future.
