### ISSUE TITLE
Support for Json6902 patches

### ISSUE THREAD

**Issue by elisiano** [replicatedhq/ship#730]
### Expected behavior
A way to specify JSON6902 patches ([supported](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md) by kustomize)
### Actual behavior
Currently it's not possible to specify anything but a strategic merge patch
### Information

- Ship version: 0.25.2

This might fix also #412

**Comment by marccampbell** [comment]
Agreed. We can target adding this in an upcoming release.
