### ISSUE TITLE
ValidationError - got map expected array; after overriding {} with [] for Helm values

### ISSUE THREAD

**Issue by nictrix** [replicatedhq/ship#777]
Hi,

Awesome project! I just started working with it and need some help understanding if this is a bug in the Helm Chart or how Replicated Ship is handling default Helm values when trying to override them.

I'm using: https://github.com/helm/charts/tree/master/stable/kibana

And it has a default value of `env: {}`, but Kubernetes doesn't like that, so it errors out with the message `got "map", expected "array"`

I made a Helm values.yaml file with `env: []`, but when looking at `.ship/state.json` I don't see the Helm value being updated, so it still comes out like: `- env: {}`

Instead, I added a Kustomize patch that changes `env: {}` to `env: []`

**Should Replicated Ship be overriding the default value from: `{}` to `[]` - even though they are both nil?**

_On a side note, I looked at what the value comes out to be when Helm is using the same Helm Chart and it shows: `env: ` - which is successfully applied to the Kubernetes cluster._

### Expected behavior

```sh
>kubectl apply -f rendered.yaml
configmap/kibana created
service/kibana created
deployment.apps/kibana created
```

### Actual behavior

```sh
>kubectl apply -f rendered.yaml
configmap/kibana configured
service/kibana configured
error: error validating "rendered.yaml": error validating data: 
ValidationError(Deployment.spec.template.spec.containers[0].env): invalid type for
io.k8s.api.core.v1.Container.env: got "map", expected "array";
if you choose to ignore these errors, turn validation off with --validate=false
```

### Information

- Ship version: 
```json
{
    "version": "0.29.0",
    "git": "92f4860",
    "buildTime": "2018-12-18T00:52:50Z"
}
```

- Docker version: 

```sh
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Steps to reproduce the behavior

Not working when trying to override with helm values (tried it from the browser instead of command arguments, but that did not make a difference)

```sh
echo "env: []" > values.yaml
ship init https://github.com/helm/charts/tree/master/stable/kibana --headless --helm-values-file values.yaml
kubectl apply -f rendered.yaml
```

Working when using a Kustomize patch:

```sh
ship init https://github.com/helm/charts/tree/master/stable/kibana --headless
echo -e "patchesStrategicMerge:\n- deployment.yaml" >> overlays/ship/kustomization.yaml
echo -e 'apiVersion: apps/v1beta1\nkind: Deployment\nmetadata:\n  labels:\n    app: kibana\n    chart: kibana-1.1.0\n    heritage: Tiller\n    release: kibana\n  name: kibana\nspec:\n  template:\n    spec:\n      $setElementOrder/containers:\n      - name: kibana\n      containers:\n      - env: []\n        name: kibana\n' > overlays/ship/deployment.yaml
ship update --headless
kubectl apply -f rendered.yaml
```

**Comment by Rob0h** [comment]
Hi nictrix - That definitely seems like something that we can handle better. We'll be looking into prioritizing this in the upcoming week. Thanks!
