### ISSUE TITLE
ship init (kustomize) fails on helm/concourse (nil/null values)

### ISSUE THREAD

**Issue by nictrix** [replicatedhq/ship#801]
### Expected behavior

That ship init finishes on a default Helm Chart without any changes made.

### Actual behavior

Ship init is unable to finish as it is unable to process `nil` values that come from the Helm Chart.

### Information

- Ship version: 0.31.0
- Docker version: 18.06

### Steps to reproduce the behavior

1. `ship init --headless https://github.com/helm/charts/tree/master/stable/concourse`

### Workaround

1. `ship init --headless https://github.com/helm/charts/tree/master/stable/concourse`
2. Go to the Kustomize step, change all the values that are `null` to their proper values such as a `{}` or `[]`
3. Ship init/Kustomize will finish successfully after making the patches

I had to make changes to all of these files:
```sh
overlays/
└── ship
    ├── charts
    │   └── postgresql
    │       └── templates
    │           ├── configmap.yaml
    │           └── deployment.yaml
    ├── web-deployment.yaml
    ├── web-svc.yaml
    └── worker-statefulset.yaml
```

I don't know if this is a Helm Chart issue or Ship; seems to possibly render the Helm Chart incorrectly?

Also probably want to have a better error message come up, I did get prompted with an error once which was nice, but it was a blob of text to sift through. Ultimately I went to `.ship/debug.log` to figure it out.

**Comment by laverya** [comment]
Hmm - normally this sort of thing results in a failure _before_ reaching the `kustomize` step, not afterwards - let me look into it!

**Comment by laverya** [comment]
I can definitely see why those entries would be ending up empty, but the literal string 'null' is a bit odd.

I'm going to try and find what's creating that - it might be that it's time to bump our embedded helm version

**Comment by laverya** [comment]
When I use the version of kustomize we import, I see the same behavior running on the rendered helm templates - kustomize adds 'null' in those areas. (which, of course, produces output yaml that it can't/won't parse)

This is particularly irritating with the postgres deployment in this example - since in that situation, it takes `args: []` (ship added the `[]` during the helm template process) and replaces it with `args: null`. Definitely something we need to figure out

**Comment by laverya** [comment]
I've seen the same behavior in `kustomize` standalone: https://github.com/kubernetes-sigs/kustomize/issues/732

We might still need to do a workaround in Ship, though - depends on whether that's something they consider in need of a fix
