### ISSUE TITLE
Non-kubernetes yaml files causes errors

### ISSUE THREAD

**Issue by justyns** [replicatedhq/ship#828]
### Expected behavior

- Cloning a repository that contains files like `.travis.yml` should work as expected

### Actual behavior

- Cloning a repository that has `.travis.yml` in the root causes `base/kustomization.yaml` to have `.travis.yml` in the `resources:` list.   This results in this error:

```
ts=2019-02-11T16:40:12.388954Z caller=github.com/replicatedhq/ship/pkg/lifecycle/daemon/routes_navcycle_getstep.go level=error event=preExecute.fail err="initial kustomize run: build overlay: run kustomize: failed to run kustomize build: make customized res map: accumulateTarget: rawResources failed to read Resources: YAML file [.travis.yml] encounters a format error.\nerror unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{\"before_install\":[\"go get golang.org/x/lint/golint\",\"go get honnef.co/go/tools/cmd/staticcheck\",\"go get -u github.com/golang/dep/cmd/dep\",\"make go-dependencies\"],\"cache\":{\"directories\":[\"vendor\"]},\"go\":[\"1.10.x\",\"1.11.x\",\"master\"],\"language\":\"go\",\"matrix\":{\"allow_failures\":[{\"go\":\"master\"}],\"fast_finish\":true},\"script\":[\"make verify\"],\"sudo\":false}'\n\n\n"
```

- If I edit `base/kustomization.yaml` and remove `.travis.yml` from the resources list, `kustomize build base/` works without any issue.  However, I don't see a way to remove that file from the list and then re-run ship.  Running `ship update --headed` just causes it to re-add `.travis.yml` to the list and run into the same error again.

### Information

- Ship version: `0.32.0`
- Docker version: ...
- Command line run: `ship init --log-level debug <repo>`

### Steps to reproduce the behavior

1. Create a new directory and cd into it
2. Try running ship init with jenkins-operator as an example:  `ship init --log-level debug https://github.com/VirtusLab/jenkins-operator`

### Other

I'm not sure if there's a better way to handle this, but my initial thought is that by default files like `.travis.yml` would be ignored.   Maybe any `.yml` files that start with a dot should be ignored?  There are a lot of CI-related yaml files that will probably cause the same error.

Ideally this would also be configurable so we can pass in a list of files to ignore/exclude.

**Comment by laverya** [comment]
This is a really good suggestion, thanks! Currently we just include every `.yml`/`.yaml` file in our generated kustomize manifests, but it wouldn't be hard to attempt to parse each file as a generic k8s yaml and check for the presence of a `kind` key.

**Comment by justyns** [comment]
Side-note:  A coworker pointed out that I can use `ship init https://github.com/VirtusLab/jenkins-operator/tree/master/deploy` to point to a specific directory which gets around the error.  I imagine this won't be the case with every repo, but definitely good to know!

**Comment by marccampbell** [comment]
This is a good point that could make it difficult to figure out how to use Ship.

I wonder if Ship could scan the cloned repo, looking for hints to interpret the intent of the init command. Today, Ship takes the upstream provided on the init command very literally. 

For example, if there's a sub-directory in the repo that contains a Helm `Chart.yaml`, then it's a Helm v2 chart and would the expected behavior of Ship be to deploy this chart and ignore the rest of the repo? Or if Ship find a ship.yaml somewhere, should it target this, even if there are other files in the repo? There's possibly even a solution that works with the jenkins-operator repo referenced in this issue also, following common patterns of looking for a directory full of k8s yaml and starting there.

This is an item we'd like to have Ship be better at, and we don't do much for it today.

**Comment by justyns** [comment]
Thanks for the comments @marccampbell!  From a UX perspective, I think it would be nice if ship scanned the upstream and then prompted the user if there are multiple possibilities.

For example, if I tried to `ship init https://github.com/helm/charts/tree/master/stable` right now, it probably wouldn't be a good time.  But ship could detect multiple `Chart.yaml` files and then prompt the user to select one of them.  This would be less work on ship's part, since it wouldn't have to make guesses about the user's intention.  After a user chooses, I'd assume maybe the upstream target would just change to include the sub directory chosen.

With a repo like jenkins-operator, I obviously expected it to work by targeting the root - but I would've been okay with a prompt asking if I wanted to target the root or `deploy/` which was a directory full of yaml files.
