### ISSUE TITLE
Ship init: "We were unable to apply your patch"

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#831]
### Expected behavior

- ship init
- navigate to `/kustomize`
- create a patch
- click "save patch"
- Creating a patch in the UI completes without error, "Show Diff" drawer shows the diff

### Actual behavior

When clicking "save patch" or "save and continue", patches are persisted and rendered properly, but an error is shown in the UI, and the Diff view shows all red. The error is especially confusing.

I believe there's a 500 coming back from the `/apply` endpoint that is used to render the patched yaml for showing the diff.

![screen shot 2019-02-18 at 10 49 22 am](https://user-images.githubusercontent.com/3730605/52971066-e56a2700-336a-11e9-85b5-79bb269aa022.png)

![screen shot 2019-02-18 at 10 34 46 am](https://user-images.githubusercontent.com/3730605/52970965-8c9a8e80-336a-11e9-88cb-df0bd503f13c.png)

### Information

- Ship version: 

```json
{
    "version": "0.33.1",
    "git": "57fe3a3",
    "buildTime": "2019-02-18T18:26:06Z"
}
```

- Command line run

```
ship init github.com/replicatedhq/enterprise-gtm-starter
```

**Comment by GERey** [comment]
👍 to fixing this.  It would be much less confusing if the error didn't show up

**Comment by laverya** [comment]
I've reproduced this with `https://github.com/shipapps/signal-sciences`
It seems that this happens with ship.yaml upstreams, but not when we use the default lifecycle for helm charts / kubernetes yaml - I'll look into why

**Comment by laverya** [comment]
I think this is partly related to replicatedhq/ship#841 - the upstream I reproduced with is creating files outside of the root directory. My guess is that some code is respecting the render root properly, while other code isn't - and that's leading to the error.

```
{"caller":"github.com/replicatedhq/ship/pkg/lifecycle/daemon/routes_navcycle_kustomize.go","err":"failed to run kustomize build: make customized res map: couldn't make loader for ../../base: absolute path error in '<redacted>/signalsciences/base' : evalsymlink failure on '<redacted>/signalsciences/base' : lstat <redacted>/signalsciences/base: no such file or directory\n","event":"failed to merge patch with base","level":"error","ts":"2019-02-22T20:42:51.524326Z"}
```

**Comment by dexhorthy** [comment]
Also happens on https://github.com/replicatedhq/replicated-starter-ship
