### ISSUE TITLE
Kustomize 2.0 migration issue

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#865]
As noted in https://github.com/replicatedhq/ship/issues/859, Ship is still on the 1.x branch of Kustomize.

### Questions
- Can we upgrade kustomize without breaking ship?
- If changes are required in ship code, do these also require changes to end user's state.json files or will we be able to migrate seamlessly? What are possible solutions and their costs in terms of effort or added complexity?

**Comment by laverya** [comment]
We're currently on 2.0.2, we just aren't filling out `apiVersion` and `kind` - something we should be doing though!

https://github.com/replicatedhq/ship/blob/ce0e98ade7d08b76975cdc27ffe50b845590d908/Gopkg.toml#L90-L92

**Comment by dexhorthy** [comment]
ah gotcha, nice catch -- closing then, thanks @laverya
