### ISSUE TITLE
Question regarding removal of resources when not forking

### ISSUE THREAD

**Issue by drzero42** [replicatedhq/ship#872]
I am trying out the "Ship approach" to deployment. I have run into an issue that seems to show that the "unfork" methodology might not always work:

If I want to deploy cert-manager, I can use the Helm chart or the provided YAML. The newer versions of cert-manager requires their CRDs to be loaded before installing the Helm chart, because Helm doesn't handle CRDs very well. Mixing upstream maintained YAML and a Helm chart does not look like Ship can handle automatically, meaning manually keeping patches updated when upstream changes their YAML. Instead I could use the upstream provided YAML manifests for everything. However, the cert-manager YAML includes creation of a namespace and putting everything into that namespace. I want all "components" (ie. helper programs like cert-manager and external-dns) to go into a shared namespace that I create in a separate step in my deployment pipeline. Kustomize can change the namespaces of resources easily enough, but I want to remove the namespace resource. Removal is not supported in Kustomize - they advise forking the manifest repo and removing things there. Ship says to unfork things and just do patching. What would be the Ship recommended approach here?

**Comment by marccampbell** [comment]
Removal is supported in Ship though. Since the upstream is a Helm or K8s yaml, Ship creates the kustomization.yaml. In the `ship init` process, on the `/kustomize` step, you can "remove" a resource on file tree. All this does is tell ship to not write it as a "resource" because of the lack of removal functionality in kustomize.

I'm not 100% sure understand the CRD question. I don't have direct experience with cert-manager, maybe something unique in there. But yeah, all gitops-tooling has conflicts with CRDs because they operate in the CI pipeline vs at runtime. This is an interesting problem we've been talking about too, but don't have any strong recommendations. There are advantages to CRDs, but if the YAML can't be reviewed, it's hard to manage.

**Comment by drzero42** [comment]
Ahh! I had not noticed that I can remove resources like that in the web interface. Thank you! :)

The CRD part is mostly a question of pretty much all current tools to handle k8s tools not handling CRDs nicely. CRDs introduce a need for ordering and waiting (to avoid race conditions) that was previously not an issue, because the controllers would just wait and reconciliate independent of ordering. Now the CRDs must be loaded fully before you start to submit CRs to the apiserver.
I see that Kustomize (at least in v2+) can load the OpenAPI definitions for CRDs in order to know how to manipulate them, and they currently look to be figuring out how to handle the ordering, so CRDs are loaded before the CRs.
The issue with cert-manager is not unique - most apps that use CRDs just have their Helm chart use a hook to load the CRDs, which is fine if you just want the user/admin to be able to add CRs afterwards (example: Velero (previously Heptio Ark) where you create backup CRs to tell Velero what to backup). With cert-manager the problem is that finalizing a deployment of cert-manager itself requires creating some CRs, which means the CRDs must be installed before the rest, which Helm does not support.
I don't understand why you don't think CRD YAML can be reviewed. Isn't it just a question of doing something like what Kustomize has recently added support for, where you actually read in the OpenAPI schema for CRDs, letting you know exactly what the YAML should look like?
Sorry for the rant, but this is indeed a very interesting problem, that I hope somebody will soon find some nice solutions to :)
I'll close this issue here - a discussion about CRDs is probably better suited for a separate issue.

**Comment by dexhorthy** [comment]
@drzero42 lot of interesting thoughts here. Ship does have a way to combine multiple disparate upstreams into a single ship "app". This method could let you track the cert-manager chart and the CRDs with a single state.json / kustomixze overlay.

I don't have a *great* example, but I had a thought to do this for cert-manager after deploying it myself last week. There are a few examples in https://github.com/shipapps but I'd be happy to see if we can create a repo for cert-manager there and we can collaborate on trying to put something together. 

Thoughts @marccampbell ?

**Comment by drzero42** [comment]
@dexhorthy That looks very interesting. I've tried creating a ship app for the external-dns helm chart, but it looks like something isn't completely done. The values_from attribute for helm in ship.yaml looks like it is pretty much undocumented and unfinished, as no matter what I put in there it complains. If I leave out a values file, I can package things together nicely like this, but not being able to use a values file is unfortunately a deal breaker.

**Comment by dexhorthy** [comment]
@drzero42 yeah, the docs and examples are a bit lacking on that stuff. We do have an end to end example of this working with consul if you wanted to use that as a starting point: https://github.com/replicatedhq/ship/blob/master/fixtures/sv-helm-values/ship.yaml

You'll notice there's a pretty awful hack in there that we have an open issue for in #857

**Comment by drzero42** [comment]
@dexhorthy I think I understand what is going on there, but I am not entirely sure how to achieve our goal. I have a file which contains the values I want to render the chart with - what would in a standard helm install command would be "-f my-values.yaml". Helm will merge the default values.yaml with my-values.yaml. I have tried with this ship.yaml:
```
---
assets:
  v1: []

config: {}

lifecycle:
  v1:
    - render:
        root: ./
        assets:
          v1:
            - helm:
                dest: ./installer/base
                helm_fetch:
                  chart_ref: external-dns
                  repo_url: https://kubernetes-charts.storage.googleapis.com
                  version: "1.7.0"
                values_from:
                  path: ./external-dns-values.yaml
```
But this just gives this error: `execute render step: execute plan: execute templating: copy state value to tmp directory .ship/tmp/chartrendered: write values.yaml to external-dns-values.yaml/values.yaml: open external-dns-values.yaml/values.yaml: not a directory`.
How do I replicate `helm install -f my-values.yaml stable/external-dns` ?

**Comment by dexhorthy** [comment]
@drzero42 aha -- interesting. I think this is super close, and what you're doing is exactly what I have tried in the past. The weird gotcha here is that 

```
                values_from:
                  path: ./external-dns-values.yaml
```

only supports a directory containing a `values.yaml`, so if you wanted to make this work today you could organize like 

```
.
└── my-values
    └── values.yaml
```
```
                values_from:
                  path: ./my-values # must be a directory
```

(I agree that this is a little confusing, and I've made the same mistake myself in the past)

**Comment by drzero42** [comment]
@dexhorthy It seems that the values_from directive doesn't do what I need, after I've created a my-values directory and put external-dns-values.yaml into that and renamed it to values.yaml. When I've run `ship app --runbook ship.yaml` it grabs values.yaml from the chart and overwrites my values.yaml. Is it just me that's confused about the process or is this also a bug? :)

**Comment by dexhorthy** [comment]
@drzero42  thanks for digging into this some more -- that sounds unexpected. I'll try to dig into this some more.

**Comment by dexhorthy** [comment]
@drzero42 I am not sure about that behavior you mentioned, and we'll probably have to dig into it a bit more.

In the meantime, I've published a [basic ship.yaml for cert manage](https://github.com/shipapps/cert-manager/blob/master/ship.yaml)r that might serve as a good starting point

**Comment by azkore** [comment]
Is it possible to remove resources using ship.yaml?
