### ISSUE TITLE
Ship (sometimes) discards CRDs

### ISSUE THREAD

**Issue by drzero42** [replicatedhq/ship#873]
### Expected behavior
CDRs should be kept in base.

### Actual behavior
CRDs are (sometimes) thrown away

### Information

- Ship version: 0.36.0

I've run into a problem when trying to use ship with the cert-manager upstream YAML manifests. When I do ship init with the full YAML manifest in the cert-manager github repo, it throws away the CustomResourceDefinitions. When I try ship init with the YAML from their repo that contains just the CRDs they are preserved. 

### Steps to reproduce the behavior

Example where ship throws the CRDs away:
1. `ship init --headless github.com/jetstack/cert-manager/deploy/manifests/cert-manager.yaml`
2. `wget https://github.com/jetstack/cert-manager/blob/master/deploy/manifests/cert-manager.yaml`
3. `grep -rl CustomResourceDefinition *`
4. Only cert-manager.yaml has the CRDs

Example where CRDs are kept:
1. `ship init --headless github.com/jetstack/cert-manager/deploy/manifests/00-crds.yaml`
2. `grep -rl CustomResourceDefinition *`
3. CRDs are in both base and rendered.yaml

Please note that the CRDs in 00-cdrs.yaml are the exact same that are in the very top of cert-manager.yaml.

**Comment by laverya** [comment]
This is rather odd - I'll look into it
It seems like it may be an issue with how we split up multidoc yaml files

**Comment by laverya** [comment]
Well, I can replace 'may be an issue' with 'is an issue', it seems: https://github.com/replicatedhq/ship/blob/94f6ac01d9a2fbe98e008dbf1422d07273d9015d/pkg/util/multidoc_yaml.go#L54

Now to figure out WHY we're doing that, and if we can stop
