### ISSUE TITLE
Add Sprig Template Functions to Ship Context

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#923]
Would be great to have access to [Sprig](https://github.com/masterminds/sprig) template functions in  the Ship template context.

**Comment by laverya** [comment]
Hmm. I thought we had already done, this, but apparently not
It'll need to get added to the Static context here: https://github.com/replicatedhq/ship/blob/adfa4f99f9cb10d607b6fe3808e6b8fa39b74a51/pkg/templates/static_context.go#L54

**Comment by laverya** [comment]
This was added in [v0.43.0](https://github.com/replicatedhq/ship/releases/tag/v0.43.0).
