### ISSUE TITLE
Error message in step 3 with Rook operator helm chart

### ISSUE THREAD

**Issue by Timoses** [replicatedhq/ship#931]
### Expected behavior
Ship continues to step 3

### Actual behavior
Error message displayed: 
```
execute render step: execute plan: execute templating: copy state value to tmp directory .ship/tmp/chartrendered: merge helm values: unmarshal base values: yaml: line 7: found character that cannot start any token
```

### Information

- Ship version: 
```
"version": "0.41.0",
"git": "14db0e3",
```
- Docker version: 18.06.2-ce
- Command line run: ship init https://github.com/rook/rook/tree/v1.0.0/cluster/charts/rook-ceph

### Steps to reproduce the behavior

1. Ship init  (Cloning and renaming of `values.yaml.tmpl` because of #930):
```
$ git clone https://github.com/rook/rook.git
$ mv rook/cluster/charts/rook-ceph/values.yaml.tmpl rook/cluster/charts/rook-ceph/values.yaml
$ ship init rook/cluster/charts/rook-ceph
```
2. open Browser
3. Step 2 (values): Change `image` -> `tag` to e.g. master
4. Step 3: Error message is displayed (see above)

**Comment by dexhorthy** [comment]
@Timoses it looks like that values.yaml.tmpl might not quite be valid YAML just yet, we might need to run it through whatever preproccessor fills in those `%%VERSION%%` placeholders, before running ship. (Even though you've modified the values, we still store the original values for diffing, and those have to be valid yaml).

I think the best bet would be to just remove that `%%VERSION%%` from the values file before running `ship init`. You can leave it as a placeholder, or set it to the value you need.

As mentioned in #930 there are unfortunately a few manual steps here to get the Helm Chart to a valid state.

**Comment by dexhorthy** [comment]
@Timoses another workaround is to fetch the released chart from the rook charts repo:

```shell
helm repo add rook-release https://charts.rook.io/release
helm fetch --untar rook-release/rook-ceph
ship init ./rook-ceph
```

**Comment by Timoses** [comment]
Thanks for the info!

I'm closing this issue as the error message stated where the error appeared in a reasonable manner.
