### ISSUE TITLE
No vertical scroll bar in Chrome on the kustomize step

### ISSUE THREAD

**Issue by divolgin** [replicatedhq/ship#936]
### Expected behavior
On the kustomize step, user should be able to click on any base listed on the left.

### Actual behavior
When the list is long enough, there is no scrollbar in Chrome.

### Information
Scrollbar shows up in Safari.

- Ship version: 0.42.0
- Docker version:
- Command line run:

**Comment by laverya** [comment]
This was fixed as part of [v0.47.0](https://github.com/replicatedhq/ship/releases/tag/v0.47.0).
