### ISSUE TITLE
Update workflow: Updating via URL or git branch/tag

### ISSUE THREAD

**Issue by Timoses** [replicatedhq/ship#987]
### Expected behavior
I'd like to only use a specific git release branch/tag (or URL) and later manually update.

### Actual behavior
Currently, I do not see an option to either:
* set the URL to another one: E.g. updating from istio `1.1.0` to `1.2.0` by changing the URL from `https://github.com/istio/istio/tree/1.1.0/install/kubernetes/helm/istio-init` to `https://github.com/istio/istio/tree/1.2.0/install/kubernetes/helm/istio-init`
* specifying git branch/tag

One could `ship init` again, however `base` directory has to be deleted or `--rm-asset-dest` be used. Further, the helm `namespace` is not stored. I'm uncertain if values are persisted when using this "update" mechanism.

### Information

- Ship version: 0.44.0
- Docker version: n/a
- Command line run: n/a

### Steps to reproduce the behavior
n/a

**Comment by Timoses** [comment]
I just noticed that when using `ship update` it automatically fetches a new release. How does it determine the new version? By checking out the latest SemVer Tag?

It would be great if it were possible to manually set which version (tag/branch) it uses and also to change the URL as well.

A `ship status` command perhaps could help to identify the URL and currently loaded version to make this information easily accessible to the user.

**Comment by dexhorthy** [comment]
@Timoses Ship uses the `v1.upstream` field in `.ship/state.json`. For semver-tagged charts like Istio, it will in general fetch the latest when running `ship update` or `ship update --headed`. There is also a `ship edit` command that can be used to modify your config without fetching a new version of the upstream.

**Comment by Timoses** [comment]
Thanks for explanation @dexhorthy .

So it is actually not possible to track a specific branch or tag. Well, initially when using `ship init URL` it will use the tree/commit/... specified in the URL. But since the URL is stored in the state as `__latest__` a `ship update` will simply jump to the latest commit on a `ship update`.

I found this issue: https://github.com/replicatedhq/ship/issues/784
I believe that already resolves around the same issue. So feel free to close this issue.

**Comment by dexhorthy** [comment]
Aye, you've got it I think. One small correction that is unfortunately not documented anywhere is that `__latest__` means "fetch the latest tagged semver release", not necessarily the latest commit. Anyhow, I think you're on to something in #784 , so we can continue over there.
